# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity/stream_message_code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n entity/stream_message_code.proto\x12\x04grpc*\xe2\x01\n\x11StreamMessageCode\x12\x08\n\x04PING\x10\x00\x12\x0c\n\x08RUN_TASK\x10\x01\x12\x0f\n\x0b\x43\x41NCEL_TASK\x10\x02\x12\x0f\n\x0bINSERT_DATA\x10\x03\x12\x0f\n\x0bINSERT_LOGS\x10\x04\x12\x0e\n\nSEND_EVENT\x10\x05\x12\x12\n\x0eINSTALL_PLUGIN\x10\x06\x12\x14\n\x10UNINSTALL_PLUGIN\x10\x07\x12\x10\n\x0cSTART_PLUGIN\x10\x08\x12\x0f\n\x0bSTOP_PLUGIN\x10\t\x12\x0b\n\x07\x43ONNECT\x10\n\x12\x0e\n\nDISCONNECT\x10\x0b\x12\x08\n\x04SEND\x10\x0c\x42\x08Z\x06.;grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity.stream_message_code_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006.;grpc'
  _STREAMMESSAGECODE._serialized_start=43
  _STREAMMESSAGECODE._serialized_end=269
# @@protoc_insertion_point(module_scope)
