# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11models/task.proto\x12\x04grpc\"\xb4\x01\n\x04Task\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x11\n\tspider_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07node_id\x18\x06 \x01(\t\x12\x0b\n\x03\x63md\x18\x08 \x01(\t\x12\r\n\x05param\x18\t \x01(\t\x12\r\n\x05\x65rror\x18\n \x01(\t\x12\x0b\n\x03pid\x18\x10 \x01(\x05\x12\x10\n\x08run_type\x18\x11 \x01(\t\x12\x13\n\x0bschedule_id\x18\x12 \x01(\t\x12\x0c\n\x04type\x18\x13 \x01(\tB\x08Z\x06.;grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006.;grpc'
  _TASK._serialized_start=28
  _TASK._serialized_end=208
# @@protoc_insertion_point(module_scope)
